# Known answers from the Julia reference (helper-hdp-known-answers.R,
# generated by tools/hdp_known_answers.jl in the analysis repo). Same
# hand-built data, same explicit start, so no random stream is involved and
# the R fit must reproduce the reference value for value: every iteration's
# ELBO, the iteration count, theta, pi, beta and the hard assignments.
#
# These are what pin the update equations (the alpha/gamma terms, the stick
# tails) and the stopping rule; the seed-agreement checks on real data cannot
# tell a slightly wrong update from seed noise. The flat cases' ELBO dips, so
# a best-ELBO stopping rule sees "no improvement" there; in
# eb_q3_p29_a1.3_g0.7 it would stop at iteration 14, not the reference's 26.

# Restated from tools/hdp_known_answers.jl: 60 records x 9 items in three
# blocks; block items present unless (i * j) %% q == 0, others present when
# (i + 2j) %% 11 == 0. Groups: records 1-30, 31-60.
ka_x <- function(n = 60L, q = 5L) {
  x <- matrix(FALSE, n, 9L)
  for (i in seq_len(n)) {
    for (j in 1:9) {
      in_block <- (j - 1L) %/% 3L == i %% 3L
      x[i, j] <- if (in_block) (i * j) %% q != 0L else (i + 2L * j) %% 11L == 0L
    }
  }
  x
}
ka_init <- function(n = 60L, k = 6L, p = 17L) {
  outer(seq_len(n), seq_len(k), function(i, kk) ((i * 7 + kk * 13) %% p + 1) / (p + 1))
}
ka_group <- rep(1:2, each = 30L)

ka_fit <- function(case, max_iter = 300L) {
  fit_hdp_bernoulli_mixture(ka_x(q = case[["q"]]), ka_group, 2L, k_max = 6L,
                            prior = case[["prior"]], alpha = case[["alpha"]],
                            gamma = case[["gamma"]], n_init = 1L, max_iter = max_iter,
                            tol = 1e-5, init = ka_init(p = case[["p"]]))
}

for (name in names(hdp_known_answers)) {
  test_that(sprintf("known answer from the reference: %s", name), {
    want <- hdp_known_answers[[name]]
    got <- ka_fit(want)
    expect_identical(got[["n_iter"]], want[["n_iter"]])
    expect_identical(got[["converged"]], want[["converged"]])
    expect_equal(got[["elbo_trace"]], want[["elbo_trace"]], tolerance = 1e-9)
    expect_equal(got[["elbo"]], want[["elbo_trace"]][[want[["n_iter"]]]], tolerance = 1e-9)
    expect_equal(got[["theta"]], want[["theta"]], tolerance = 1e-9)
    expect_equal(got[["pi_mean"]], want[["pi_mean"]], tolerance = 1e-9)
    expect_equal(got[["beta_mean"]], want[["beta_mean"]], tolerance = 1e-9)
    expect_identical(got[["assignments"]], want[["assignments"]])
    expect_identical(got[["effective_k"]], want[["effective_k"]])
  })
}

test_that("known answers: one case separates the per-step and best-ELBO stopping rules", {
  # Replay the pinned trace under both rules (5 steps each below
  # tol * (1 + |previous|)): the reference's stops where the fixture says, a
  # best-ELBO rule much earlier. If a regenerated fixture lost this, that
  # plant would pass unnoticed.
  tr <- hdp_known_answers[["eb_q3_p29_a1.3_g0.7"]][["elbo_trace"]]
  first_stop <- function(best) {
    for (n in 6:length(tr)) {
      small <- vapply((n - 4L):n, function(i) {
        d <- if (best) tr[[i]] - max(tr[seq_len(i - 1L)]) else abs(tr[[i]] - tr[[i - 1L]])
        d < 1e-5 * (1 + abs(tr[[i - 1L]]))
      }, logical(1))
      if (all(small)) return(n)
    }
    NA_integer_
  }
  expect_identical(first_stop(best = FALSE), length(tr))
  expect_lt(first_stop(best = TRUE), length(tr) - 5L)
})

test_that("known answers: an explicit init is validated", {
  x <- ka_x()
  expect_error(fit_hdp_bernoulli_mixture(x, ka_group, 2L, k_max = 6L, n_init = 2L,
                                         init = ka_init()), "n_init = 1")
  expect_error(fit_hdp_bernoulli_mixture(x, ka_group, 2L, k_max = 5L, n_init = 1L,
                                         init = ka_init()), "60 x 5")
  bad <- ka_init()
  bad[1, 1] <- 0
  expect_error(fit_hdp_bernoulli_mixture(x, ka_group, 2L, k_max = 6L, n_init = 1L, init = bad),
               "positive")
})

test_that("known answers: hdp_clustering maps an init to records by group and id", {
  x <- ka_x()
  items <- paste0("i", 1:9)
  ev <- do.call(rbind, lapply(which(rowSums(x) > 0), function(i) {
    data.frame(id = i, item = items[x[i, ]], Group = c("A", "B")[ka_group[[i]]])
  }))
  m <- record_item_matrix(ev)
  n <- nrow(m[["x"]])
  tab <- data.frame(group = m[["group_labels"]][m[["group"]]], id = m[["ids"]], ka_init(n))
  fit <- function(init) {
    hdp_clustering(ev, k_max = 6L, prior = "flat", alpha = 1.3, gamma = 0.7, n_init = 1L,
                   init = init)[["hdp"]]
  }
  # The same start, given in table order or shuffled, is the same fit: the
  # start follows the record, not the row. And it equals the direct fit on
  # the record matrix from that start.
  in_order <- fit(tab)
  shuffled <- fit(tab[rev(seq_len(n)), ])
  direct <- fit_hdp_bernoulli_mixture(m[["x"]], m[["group"]], 2L, k_max = 6L, prior = "flat",
                                      alpha = 1.3, gamma = 0.7, n_init = 1L, init = ka_init(n))
  expect_identical(shuffled[["elbo_trace"]], in_order[["elbo_trace"]])
  expect_identical(in_order[["elbo_trace"]], direct[["elbo_trace"]])
  expect_identical(in_order[["assignments"]], direct[["assignments"]])
  expect_error(fit(tab[-1L, ]), "1 missing")
  expect_error(fit(rbind(tab, tab[1L, ])), "more than once")
})
